/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type BodyOverridesProps = {
    "123456"?: PrimitiveOverrideProps<TextProps>;
    Body?: PrimitiveOverrideProps<FlexProps>;
    Title?: PrimitiveOverrideProps<FlexProps>;
    Jobs?: PrimitiveOverrideProps<TextProps>;
    "Frame 1948756988"?: PrimitiveOverrideProps<FlexProps>;
    Button?: PrimitiveOverrideProps<FlexProps>;
    add?: PrimitiveOverrideProps<ViewProps>;
    Vector94589?: PrimitiveOverrideProps<IconProps>;
    "Accept order94590"?: PrimitiveOverrideProps<TextProps>;
    "Frame 55"?: PrimitiveOverrideProps<FlexProps>;
    "Filter v294592"?: PrimitiveOverrideProps<FlexProps>;
    send?: PrimitiveOverrideProps<ViewProps>;
    Vector94594?: PrimitiveOverrideProps<IconProps>;
    Dispatch94595?: PrimitiveOverrideProps<TextProps>;
    arrow_drop_down94596?: PrimitiveOverrideProps<ViewProps>;
    Vector94597?: PrimitiveOverrideProps<IconProps>;
    "Filter v294598"?: PrimitiveOverrideProps<FlexProps>;
    engineering?: PrimitiveOverrideProps<ViewProps>;
    Vector94600?: PrimitiveOverrideProps<IconProps>;
    Dispatch94601?: PrimitiveOverrideProps<TextProps>;
    arrow_drop_down94602?: PrimitiveOverrideProps<ViewProps>;
    Vector94603?: PrimitiveOverrideProps<IconProps>;
    "Filter v294604"?: PrimitiveOverrideProps<FlexProps>;
    tag?: PrimitiveOverrideProps<ViewProps>;
    Vector94606?: PrimitiveOverrideProps<IconProps>;
    Dispatch94607?: PrimitiveOverrideProps<TextProps>;
    arrow_drop_down94608?: PrimitiveOverrideProps<ViewProps>;
    Vector94609?: PrimitiveOverrideProps<IconProps>;
    "Filter v294610"?: PrimitiveOverrideProps<FlexProps>;
    build?: PrimitiveOverrideProps<ViewProps>;
    Vector94612?: PrimitiveOverrideProps<IconProps>;
    Dispatch94613?: PrimitiveOverrideProps<TextProps>;
    arrow_drop_down94614?: PrimitiveOverrideProps<ViewProps>;
    Vector94615?: PrimitiveOverrideProps<IconProps>;
    "Filter v294616"?: PrimitiveOverrideProps<FlexProps>;
    location_on?: PrimitiveOverrideProps<ViewProps>;
    Vector94618?: PrimitiveOverrideProps<IconProps>;
    Dispatch94619?: PrimitiveOverrideProps<TextProps>;
    arrow_drop_down94620?: PrimitiveOverrideProps<ViewProps>;
    Vector94621?: PrimitiveOverrideProps<IconProps>;
    "Frame 26080094"?: PrimitiveOverrideProps<FlexProps>;
    Tab94623?: PrimitiveOverrideProps<FlexProps>;
    Call94624?: PrimitiveOverrideProps<FlexProps>;
    Details94625?: PrimitiveOverrideProps<TextProps>;
    "Add info94626"?: PrimitiveOverrideProps<FlexProps>;
    home_repair_service94627?: PrimitiveOverrideProps<ViewProps>;
    Vector94628?: PrimitiveOverrideProps<IconProps>;
    "Refrigerator repair94629"?: PrimitiveOverrideProps<TextProps>;
    Tab94630?: PrimitiveOverrideProps<FlexProps>;
    Call94631?: PrimitiveOverrideProps<FlexProps>;
    Details94632?: PrimitiveOverrideProps<TextProps>;
    "Frame 194875700794633"?: PrimitiveOverrideProps<FlexProps>;
    home_repair_service94634?: PrimitiveOverrideProps<ViewProps>;
    Vector94635?: PrimitiveOverrideProps<IconProps>;
    "Add info94636"?: PrimitiveOverrideProps<FlexProps>;
    "Refrigerator repair94637"?: PrimitiveOverrideProps<TextProps>;
    Tab94638?: PrimitiveOverrideProps<FlexProps>;
    Call94639?: PrimitiveOverrideProps<FlexProps>;
    Details94640?: PrimitiveOverrideProps<TextProps>;
    "Frame 194875700794641"?: PrimitiveOverrideProps<FlexProps>;
    home_repair_service94642?: PrimitiveOverrideProps<ViewProps>;
    Vector94643?: PrimitiveOverrideProps<IconProps>;
    "Add info94644"?: PrimitiveOverrideProps<FlexProps>;
    "Refrigerator repair94645"?: PrimitiveOverrideProps<TextProps>;
    Tab94646?: PrimitiveOverrideProps<FlexProps>;
    Call94647?: PrimitiveOverrideProps<FlexProps>;
    Details94648?: PrimitiveOverrideProps<TextProps>;
    "Frame 194875700794649"?: PrimitiveOverrideProps<FlexProps>;
    home_repair_service94650?: PrimitiveOverrideProps<ViewProps>;
    Vector94651?: PrimitiveOverrideProps<IconProps>;
    "Add info94652"?: PrimitiveOverrideProps<FlexProps>;
    "Refrigerator repair94653"?: PrimitiveOverrideProps<TextProps>;
    "Frame 26080082"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 1948757010"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 61"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 594657"?: PrimitiveOverrideProps<FlexProps>;
    Checkbox94658?: PrimitiveOverrideProps<FlexProps>;
    "Frame 6094659"?: PrimitiveOverrideProps<ViewProps>;
    All?: PrimitiveOverrideProps<TextProps>;
    "Frame 4"?: PrimitiveOverrideProps<FlexProps>;
    "Job ID"?: PrimitiveOverrideProps<TextProps>;
    "Frame 694663"?: PrimitiveOverrideProps<FlexProps>;
    Client?: PrimitiveOverrideProps<TextProps>;
    "Frame 794665"?: PrimitiveOverrideProps<FlexProps>;
    Tags?: PrimitiveOverrideProps<TextProps>;
    "Frame 894667"?: PrimitiveOverrideProps<FlexProps>;
    "Job type"?: PrimitiveOverrideProps<TextProps>;
    "Frame 994669"?: PrimitiveOverrideProps<FlexProps>;
    Scheduled?: PrimitiveOverrideProps<TextProps>;
    "Frame 1094671"?: PrimitiveOverrideProps<FlexProps>;
    Phone?: PrimitiveOverrideProps<TextProps>;
    "Frame 1194673"?: PrimitiveOverrideProps<FlexProps>;
    Email?: PrimitiveOverrideProps<TextProps>;
    "Frame 1294675"?: PrimitiveOverrideProps<FlexProps>;
    Tech?: PrimitiveOverrideProps<TextProps>;
    "Frame 1394677"?: PrimitiveOverrideProps<FlexProps>;
    "Create by"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1494679"?: PrimitiveOverrideProps<FlexProps>;
    Address?: PrimitiveOverrideProps<TextProps>;
    "Frame 1594681"?: PrimitiveOverrideProps<FlexProps>;
    "Service area"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1694683"?: PrimitiveOverrideProps<FlexProps>;
    Sourse94684?: PrimitiveOverrideProps<TextProps>;
    "Frame 1794685"?: PrimitiveOverrideProps<FlexProps>;
    "Time in status94686"?: PrimitiveOverrideProps<TextProps>;
    "Frame 18"?: PrimitiveOverrideProps<FlexProps>;
    Location94688?: PrimitiveOverrideProps<TextProps>;
    "Frame 62"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 594690"?: PrimitiveOverrideProps<FlexProps>;
    Checkbox94691?: PrimitiveOverrideProps<FlexProps>;
    "Frame 6094692"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 21"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 694695"?: PrimitiveOverrideProps<FlexProps>;
    "Ronald Richards"?: PrimitiveOverrideProps<TextProps>;
    "Frame 794697"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 30"?: PrimitiveOverrideProps<FlexProps>;
    Tag94699?: PrimitiveOverrideProps<FlexProps>;
    "Accept order94700"?: PrimitiveOverrideProps<TextProps>;
    Tag94702?: PrimitiveOverrideProps<FlexProps>;
    "Accept order94703"?: PrimitiveOverrideProps<TextProps>;
    Tag94705?: PrimitiveOverrideProps<FlexProps>;
    "Accept order94706"?: PrimitiveOverrideProps<TextProps>;
    Tag94708?: PrimitiveOverrideProps<FlexProps>;
    "Accept order94709"?: PrimitiveOverrideProps<TextProps>;
    "Frame 36"?: PrimitiveOverrideProps<FlexProps>;
    more_horiz?: PrimitiveOverrideProps<ViewProps>;
    Vector94713?: PrimitiveOverrideProps<IconProps>;
    "Frame 894714"?: PrimitiveOverrideProps<FlexProps>;
    "Wine(cigar)cooler repair"?: PrimitiveOverrideProps<TextProps>;
    "Frame 994716"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 63"?: PrimitiveOverrideProps<FlexProps>;
    event?: PrimitiveOverrideProps<ViewProps>;
    Vector94719?: PrimitiveOverrideProps<IconProps>;
    "Fri, Jul 17, 2024"?: PrimitiveOverrideProps<TextProps>;
    "Frame 64"?: PrimitiveOverrideProps<FlexProps>;
    access_time?: PrimitiveOverrideProps<ViewProps>;
    Vector94723?: PrimitiveOverrideProps<IconProps>;
    "8:00\u00A0AM"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1094725"?: PrimitiveOverrideProps<FlexProps>;
    "(808) 555-0111"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1194727"?: PrimitiveOverrideProps<FlexProps>;
    "curtis.weaver@example.com"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1294729"?: PrimitiveOverrideProps<FlexProps>;
    "Alex Fazylkhatov"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1394731"?: PrimitiveOverrideProps<FlexProps>;
    "Cameron Williamson"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1494733"?: PrimitiveOverrideProps<FlexProps>;
    "2464 Royal Ln. Mesa, New Jersey 45463"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1594735"?: PrimitiveOverrideProps<FlexProps>;
    "New Jersey"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1694737"?: PrimitiveOverrideProps<FlexProps>;
    Sourse94738?: PrimitiveOverrideProps<TextProps>;
    "Frame 1794739"?: PrimitiveOverrideProps<FlexProps>;
    "Time in status94740"?: PrimitiveOverrideProps<TextProps>;
    "Frame 20"?: PrimitiveOverrideProps<FlexProps>;
    Location94742?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type BodyProps = React.PropsWithChildren<Partial<FlexProps> & {
    overrides?: BodyOverridesProps | undefined | null;
}>;
export default function Body(props: BodyProps): React.ReactElement;
